# Created using wingetcreate 1.0.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: OpenJS.NodeJS
PackageVersion: 16.17.0
InstallerLocale: en-US
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerType: wix
  InstallerUrl: https://nodejs.org/dist/v16.17.0/node-v16.17.0-x64.msi
  InstallerSha256: FF2FFAF555E11311B3381E85D660D870DFC28DBB78AE9FB7B472250B5B0DFF4F
  ProductCode: '{F55EB18F-3933-4530-90D4-4075D19AF3E7}'
- Architecture: x86
  InstallerType: wix
  InstallerUrl: https://nodejs.org/dist/v16.17.0/node-v16.17.0-x86.msi
  InstallerSha256: 4E8F5BB4A76AA7FB164B20362FA51B27F3113C7225F18123929DF2D9B5EAA1AA
  ProductCode: '{CBB49067-4AAF-4850-858A-ADCBF65BDB99}'
ManifestType: installer
ManifestVersion: 1.1.0

